### ISSUE TITLE
"True" should be "Yes", False should be "No"

### ISSUE THREAD

**Issue by href** [seantis/seantis.translators#7]
> Wenn ich bei der Zustimmung Namensbekanntgabe anklicke, erscheint beim Ausdruck das Wort True, es sollte aber Ja oder Nein erscheinen.

I thought this worked already.. there must be a bug.

**Comment by msom** [comment]
Fixed with seantis/seantis.people@7a5c426badc61fb7e3587264b42b24b8efadc89f

**Comment by href** [comment]
True in "True, False, Unknown" seems to be rendered fine, but False is not rendered at all (the whole field disappears). Can you have a look at this?

**Comment by href** [comment]
Nevermind, I fixed the problem with https://github.com/seantis/seantis.people/commit/e1683d053ceb193691a0eeee24c0280f9bff2f5e

Though this is not ideal "None" would still not be rendered if it was a correct answer. For that the renderers would have to deal with empty values themselves and return something if the result should not be renderered. But for now this is good enough.
